version: '3.8'

services:
  web:
    build: ./app
    container_name: ${CONTAINER_BE_NAME}
    # Start the server
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: ${CONTAINER_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - ${SQL_PORT}:${SQL_PORT}

volumes:
  postgres:
