# Generated by Django 4.2.16 on 2024-11-19 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '__first__'),
        ('hashtags', '__first__'),
        ('keywords', '__first__'),
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='categories.category')),
                ('hashtags', models.ManyToManyField(blank=True, related_name='products', to='hashtags.hashtag')),
                ('keywords', models.ManyToManyField(blank=True, related_name='products', to='keywords.keyword')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
